# GitHub Labels Configuration
# Use: gh label sync -f .github/labels.yml

- name: "bug"
  color: "d73a4a"
  description: "Что-то работает не так, как ожидалось"

- name: "enhancement"
  color: "a2eeef"
  description: "Новая функция или запрос"

- name: "documentation"
  color: "0075ca"
  description: "Улучшения или добавления к документации"

- name: "good first issue"
  color: "7057ff"
  description: "Подходит для новичков"

- name: "help wanted"
  color: "008672"
  description: "Требуется дополнительная помощь"

- name: "question"
  color: "d876e3"
  description: "Дополнительная информация запрошена"

- name: "wontfix"
  color: "ffffff"
  description: "Это не будет исправлено"

- name: "duplicate"
  color: "cfd3d7"
  description: "Этот issue или PR уже существует"

- name: "invalid"
  color: "e4e669"
  description: "Это не похоже на правильный issue"

- name: "dependencies"
  color: "0366d6"
  description: "Обновления зависимостей"

- name: "security"
  color: "ee0701"
  description: "Проблемы безопасности"

- name: "performance"
  color: "1d76db"
  description: "Производительность"

- name: "ui/ux"
  color: "bfdadc"
  description: "UI/UX улучшения"

- name: "stale"
  color: "fef2c0"
  description: "Устаревший issue или PR"

- name: "pinned"
  color: "0e8a16"
  description: "Закреплённый, не будет автоматически закрыт"

- name: "github-actions"
  color: "000000"
  description: "GitHub Actions workflows"

- name: "automated"
  color: "ededed"
  description: "Автоматически созданный"

- name: "breaking change"
  color: "b60205"
  description: "Ломающее изменение"

- name: "needs review"
  color: "fbca04"
  description: "Требуется ревью"

- name: "work in progress"
  color: "f9d0c4"
  description: "В процессе работы"

